Vishal-raj-1/Awesome-JavaScript-Projects

index.html

Images are now visible..
https://user-images.githubusercontent.com/63122133/106457626-41c1a500-64b5-11eb-91fd-86aac2fb29e3.mp4

Corrected the images links after image folder added to assets folder

---

README.md

You can check the readme [here](https://github.com/urvashi-code1255/Awesome-JavaScript-Projects/blob/Develop/README.md)

Added GIFs and some content

---

assets/css/calculator.css
public/calculator.html

@Vishal-raj-1 Please check [here](https://urvashi-code1255.github.io/Awesome-JavaScript-Projects/public/calculator.html) and please let me know if its good to go then I will update the image of the project.

Calculator Design Updated

---

.github/PR_template.md

This PR will resolve issue #29 .

Added PR template

---

assets/css/style.css
index.html

Reduced the large gap seen in the screenshot on issue 28 between the Home and About sections to a more reasonable amount of spacing between the sections - updated version below.

Fixed spacing issue between Home and About sections

---

assets/css/counter.css
assets/js/counter.js

- Solved the issue of counter project
Closes: #32 
Changed the JS code part - The innerHTML content plus updated the id properties in CSS file ( Which should have been id but someone had used class selector )
NA

counter bug issue solve

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Closes: #70 .
Added CODE_OF_CONDUCT.md and CONTRIBUTING.md files.
NA

Added CODE_OF_CONDUCT.md and CONTRIBUTING.md files

---

assets/css/style.css
assets/js/Scroll.js
index.html

- I have added Scroll to top button to the main webpage itself
Closes: #37 
Added scroll to top button which should be visible at every part of the page(not only at the bottom).

 Added Scroll to top button

---

.github/config.yml

Integrate Welcome Bot
Closes: #92 [issue number that will be closed through this PR]
I have added config files for Welcome Bot.
NA

Add Config Files for Welcome Bot

---

assets/css/draw.css
assets/js/draw.js
public/draw.html

Closes: #137
Clear button option to clear the all drawn thing on the window for the fresh start ( New page )
NA
https://tidbitsjs.github.io/Awesome-JavaScript-Projects/

clear all the draw

---

assets/css/style.css
index.html

Closes: #143 
Created missing projects card + adjusted the heights of all cards so that they all look uniform throughout the page
NA
Link - https://tidbitsjs.github.io/Awesome-JavaScript-Projects/

Cards & Height set

---

assets/js/note-app.js
public/note-app.html

Closes: #39 
Add save button in HTML file and edit and save function in note-app.js file.
NA
https://user-images.githubusercontent.com/62712155/109027044-6391fe80-76e6-11eb-9bc7-7fcf4b2f9ec7.mp4

edit button added in note-app

---

README.md

change gif

---

assets/js/note-app.js
public/note-app.html

#177 
Closes: #177 
I added the feature to create a title for the note.

Resolving issue#177

---

assets/css/molegame.css
assets/js/molegame.js
public/molegame.html

- Whack a Mole Game is not Responsive
Closes: #188
made it responsive for all screen sizes

made Whack a Mole Game responsive for all screen sizes

---

assets/css/calculator.css
assets/css/style.css

Signed-off-by: Ankit <ankitmaurya0225@gmail.com>
Closes: #196

Smooth Transition while hovering

---

index.html

#200 
Closes: #200 
Added favicon to `index.html`
NA

Favicon added

---

public/color-flipper.html

Color flipper styling required
Closes: #181 
change the styling of  button 
NA

color flipper updated

---

assets/css/style.css
index.html
script.js

I have fixed the navbar.
- The navbar wasn't fixed.
Closes: #240
I have fixed the above particular issue though js and css.

Navbar fixed.

---

README.md

- 
Closes: #367 
I have added logo of tech stack 
NA

Added tech stack logo

---

assets/js/url.js

URL Shortner API wasn't working fine.
Closes: #190 
I've removed unnecessary functions and fixed the working of the API by providing it the URL in the correct format.
NA

URL Shortner Bug fixed

---

public/reviews.html

Reviews project was not responsive, content was getting compressed. 
Closes: #355 
I have made reviews project responsive.
NA

make reviews project responsive - #355

---

assets/js/rock-paper-sessiors.js
public/Rock-paper-sesssior.html

typo-error in rock paper scissors game
Closes: #359
I have corrected the typo error. 
- [ x]New and existing unit tests pass locally with my changes.

typo-error in rock paper scissors game

---

assets/js/calculator.js
public/calculator.html

- User doesn't have access to click on `DEL` and `AC` button using  keyboard.
Closes: #444 
Added keyboard button click shortcuts:
- `DELETE` for Del
- `END` for AC  
NA

added keyboard shortcuts for button DEL and

---

contact.html
index.html

- Adding contact us section in navbar and contact form for same.
Closes: #326 
Added one contact.html file for contact form and in index.html add contact us in navbar.
NA
@urvashi-code1255

Add contact us section in navbar and contact form for same.

---

assets/css/ExpandingCard.css
assets/js/ExpandingCard.js
public/ExpandingCard.html
script.js

Expanding Card [GSsoc 21] 

---

assets/css/quizapp.css
assets/js/quizapp.js
public/quizapp.html

- Adding a progress bar to Quiz App Project
Closes: #493
Added a progress bar with smooth transition which would indicate user's progress.
NA

Added progress bar to QuizApp

---

index.html

- Collapse plugin was not working under lower screen dimension in the navbar section.
Closes: #573 
An Id was not created for targeting the data target so that toggler button to work so i created an id of same name as that of data target.
NA

Fixed Issue number #573 (Collapse Plugin not working under Navbar section in lower screen dimension)

---

assets/css/style.css
index.html

No its not a problem. I tried to enhancing the look of navlinks.
Closes: #609 
added nav-link-ltr class in nav link tags in index.html and made the requires changes in style.css.
NA

nav links improved, hover effect added

---

assets/css/quizapp.css
assets/js/quizapp.js
public/quizapp.html

Closes: #600 [issue number that will be closed through this PR]
I have added new questions in the quizData array in the quizapp and added an enhanced functionality where random questions are picked from the array instead of the sequence wise which makes the game more interesting.
NA

new questions and random question pick feature added

---

assets/css/drumKit.css
assets/js/drumKit.js
public/drumKit.html

closes: #377
I have added a new button that will change the theme of this drumKit web app.
I have made some changes in the HTML, CSS, and js file of the drumKit web app. And it will change the theme of this by clicking the change theme button which I have added.

Added a new feature to change the theme

---

assets/js/draw.js
public/draw.html

- #372 download option for the canvas in the lets draw project.
Closes: #372 
Fixes #372 
I have made changes in draw.html file and draw.js file to add the download facility for lets draw app. so the user can download the copy of the painting he drew.
NA

Added Download button

---

index.html

Closes: #[669]
I have added a social media sticky sidebar that stays with scrolling.
NA

sticky social media sidebar added

---

public/avatarMaker.html

- The path for css and js was not accurate
fixed the path url for js,css and images

BUG fixed : In Avatar Maker project file path fixed

---

assets/css/url.css
assets/js/url.js
public/url-shortner.html

- URL Shortener at https://vishal-raj-1.github.io/Awesome-JavaScript-Projects/public/url-shortner.html is not working
Closes: #571 
Made the URL shortener working by using axios, refactored the code and added a loader on the button while the link is being shorted.
NA

fixed url shortner bug

---

assets/css/InterestCalculator.css
assets/js/InterestCalculator.js
public/InterestCalculator.html

This is a Simple Interest Calculator.

Interest Calculator

---

public/ExchangeRate.html
public/deviceInfo.html
public/memeUrl.html
public/movieSeatBooking.html
public/note-app.html
public/progressbar.html

- Assets (js,css,image) files were not able to load
Closes: #766 
Fixed the bug
NA
Assets are now loading -

Asset loading bug fixed

---

assets/css/netflix.css
public/netflix.html

issue: #278 
**Describe the changes you've made:**
Fixed the navbar to the top. Changed background of navbar and adjusted the colors of items.
**Checklist:**
- My code follows the style guidelines of this project.
-  I have performed a self-review of my own code.
-  I have commented my code, particularly in hard-to-understand areas.
-  I have made corresponding changes to the documentation.
-  New and existing unit tests pass locally with my changes.

Netflix clone navbar fixed to the top

---

assets/css/passwordGenerator.css

Fixed- #854
Screenshots
Earlier:
Now:
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri Please view my PR.

Password-generator made Responsive

---

assets/css/analogclock.css

Fixed- #854 
**Screenshots**
Earlier: 
Now:

Analog-clock made responsive

---

assets/css/digitalClock.css

- digital clock button bug
Closes: #482
I changed the color of start button & stop button before and after clicking.
**before**
**After**

digital clock button bug

---

assets/css/flipcards.css
public/flipcards.html

Fixed- #854
Screenshots
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri Please view my PR.

Updated flip-cards

---

assets/css/styles.css
index.html

Issue Number #745 
Original
Updated

Fixed Issue Number #745 (Fotter section is not allign in desktop view)

---

assets/css/calculator.css

- Make calculator project response in mobile view
Closes: #783 
I have make changes in file  calculator.css to make calculator project response in mobile view 
NA
###Befour 
###Aftar

Make calculator project response in mobile view

---

assets/css/StudyTimer.css
public/StudyTimer.html

Fixed- #854
Screenshots
Earlier:
NOW:
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri Please view my PR.

Study-Timer made responsive

---

assets/css/calculator.css
public/calculator.html

- There is a lot of animation in the calculator project, which sometimes irritates the user.
Closes: #646 
I made changes in animation in calculator project
NA

Animation reduced in calculator

---

assets/css/color-flipper.css

- color-flipper  page styling
Closes: #258 
I have add the styling to color flipper project
NA
https://user-images.githubusercontent.com/67833077/114207936-8a488380-997a-11eb-8709-816066ed3a36.mp4

color-flipper  page styling

---

assets/css/pinpad.css

Fixed- #854
Screenshots
Earlier:
NOW:
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @991rajat @ridsuteri Please view my PR.

Pin Pad made responsive

---

assets/css/Image_editor.css
public/Image_editor.html

Image Editor made responsive

---

assets/css/flipcards.css
assets/js/flipcards.js
public/flipcards.html

Fixed- #918 
Added delete button for deleting particular card.
Screenshots

Delete button added -Flip Card Project

---

assets/css/Weather_app.css
assets/js/Weather_app.js
public/Weather_app.html

Closes: #277 
I have added feature to toggle the temperature from Celsius to Fahrenheit.
The toggle feature works fine when location is detected by the browser but when the user searches for the temperature of a particular city the toggle feature shows abrupt behaviour.

Weather App toggle feature added

---

assets/css/trailer.css
public/movTrailer.html

Movie App made responsive

---

assets/css/VideoPlayer.css

Custom Video Player made responsive

---

assets/css/ColorPickerConverter.css
public/ColorPickerConverter.html

Fixed- #854
Screenshots
Earlier:
NOW:

Color Picker Converter made responsive

---

assets/css/Form_Wave_Animation.css

Fixed- #854
Screenshots
Earlier:
NOW:

Form Wave Animation Made responsive

---

assets/css/BMICalculator.css

Fixed- #854
Screenshots
Earlier:
NOW:

BMI Calculator made responsive

---

assets/css/Music_Player.css

Fixed- #854
Screenshots:
Earlier:
NOW:

Music-Player made responsive

---

assets/css/Code_Converter.css
public/Code_Converter.html

Fixed- #854
Made site responsive 
Screenshots:
Earlier:
NOW:

Code Converter made Responsive

---

assets/css/sgpa_and_cgpa.css

Fixed- #854
Made site responsive (Adjusted Background)
Screenshots:
Earlier:
NOW:

Made Cgpa & Sgpa Calculator responsive

---

assets/css/drumKit.css
public/drumKit.html

Fixed- #854
Screenshots:
Earlier:
NOW:

Made Drum-Kit responsive

---

assets/css/billsplit.css
assets/js/billsplit.js
public/billsplitter.html

Closes: #436
I have added the Bill Splitter Html application . So added:
-   assets/css/billsplit.css
-   assets/js/billsplit.js
-   public/billsplitter.html
NA

Javascript Bill Splitter Application

---

public/reviews.html

Closes: #732 
> #  Added  **MIT License** to this Repo
NA

License for Awesome-Javascript-Projects Repo.

---

assets/css/infixtopostfixandprefixconverter.css
assets/js/infixtopostfixandprefixconverter.js
public/infixtopostfixandprefixconverter.html

-Project that converts Infix to postfix/prefix using JavaScript.
Closes: [#733]

Infix to Postfix & Prefix Converter added

---

script.js

Added "JavaScript Interest Calculator" project details in the script.js file.

Updated Script.js file

---

assets/css/ExpenseTracker.css
assets/css/studentCalc.css

Fixed: #854
Screenshots:
Earlier:
NOW:

Expense tracker

---

assets/css/studentCalc.css

Fixed: #854
Screenshots:
Earlier:
NOW:

Student Grade Calcy made responsive

---

assets/css/ArmstrongNumber.css
public/ArmstrongNumber.html

Fixed #925 
UI updated and site made responsive
Screenshots:

UI Updated-Armstrong Checker

---

contact.html

I have added the placeholder  in the required fields in contact us section.
Closes: #688 
I have added the placeholder  in the required fields in contact us section.
NA

Adding placeholder in the required fields in contact us section.

---

assets/css/counter.css
public/counter.html

Closes: #1005 
improved the css of the project-Enhancing the visual of counter
NA
After the enhancement of css-

Enhanced the visual of counter

---

contact.html
index.html
projects.html
script.js

Closes: #1014 
Closes: #1012
I have fixed the GIF loading error in Projects.html on the Text to Voice Generator project as mentioned in #1012  and Fixed the Toggle button Bug as mentioned in issue #1014 
NA
Before(GIF  BUG)-
After(GIF BUG RESOLVED)-
Before(TOGGLE BUTTON BUG):-
After(TOGGLE BUTTON FIXED):-

Fixed GIF image and Toggle Button Bug

---

assets/css/ArmstrongNumber.css
assets/js/ArmstrongNumber.js
public/ArmstrongNumber.html

Fixed #990
Added Reset button in Armstrong project.
Screenshots:
NOW:

Reset button added - Armstrong Checker project

---

assets/css/DragToDo.css
assets/js/DragToDo.js
public/DragToDo.html

Fixed #965
I have added a clear option for the user which will clear the todo list from bottom to top.
Screenshots:
NOW:

Added Delete button in Drag-Drop Todo List

---

assets/css/styles.css

Navbar is blurred when scrolling down .
I have solved bug and also added animations to navbar
Closes: #998 
https://user-images.githubusercontent.com/59757988/115053424-be80ee80-9efc-11eb-88fa-5fbe73b983b3.mp4

styled navbar 

---

assets/css/AgeCalculator.css

UI age calculator updated
Closes: #1072 
UI age calculator updated
NA
after :
before :

age calculator updated

---

assets/css/harry.css
public/harry.html

harry potter page updated
Closes: #1073 
harry potter page updated 
NA

harry potter page updated

---

assets/css/noteApp.css
assets/js/note-app.js
public/note-app.html

- The styling of the note app is updated.
- Functioning of the note app which was not responding has been handled.
Closes: #713 
The styling of the page was not that attractive so I have added some CSS and hover effects along for a better view. Also, there were slight changes to be made in the javascript code due to which the notes weren't being added or edited so I have managed to fix that bug too.
NA

Note-app updated

---

assets/css/netflix.css
public/netflix.html

#939 
Closes: #939 
Nav bar
Search bar
Allignment of movies
And I had make it better and done the changes
NA

Improving Netflix app

---

assets/js/quizapp.js

There was a bug in the Quiz App due to which it was showing an incorrect score.
Closes: #1110
I have fixed the bug.
`NA`

Fixed the bug in Quiz App

---

assets/js/currecyConverter.js
public/currencyConverter.html

Fixed issue #1044 
Reset button added to currency convertor project.
Screenshots:
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri  Please view my PR

Reset button added - Currency convertor project

---

assets/css/randomuser.css

Fixed issue #1046 
Screenshots:
Earlier:
Now:

Random user made responsive

---

assets/css/molegame.css
assets/js/molegame.js
public/molegame.html

- Updated the game
Closes: #214 
Added the features mentioned in the issue
NA

Updated Whac a Mole game

---

script.js

auto arrange projects function added
Closes: #667 
https://user-images.githubusercontent.com/67833077/116029258-82752880-a676-11eb-9ad7-bd93c71a069e.mp4

auto arrange projects function added

---

assets/css/2048.css
assets/css/TypingPractice.css

Fixed issue #1046
Screenshots:
Earlier:
Now:

2048 Game Made responsive

---

assets/css/Weather_app.css

Closes: #1099 
I want to change look of search bar & button.
NA

weather app enhance

---

signuplogin.html

Fixed issue #1042 
Validations added.
Please view my PR @ridsuteri @harshgupta20

Validations added to signup/login

---

projects.html

Fixed issue #1179 
Added scroll-top in projects section 
Screenshot:
@Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri @991rajat Please view my PR

Scroll-top added in projects section

---

assets/css/StopWatch.css
public/StopWatch.html

Closes: #1161 
added screenshots related to that stuff.
-> GIF also added.
NA
LOGO

Change the Visual of Stopwatch

---

contact.html

Fixed issue #1185 
I have added validations to contact form.
Please view my PR  @Vishal-raj-1 @urvashi-code1255 @harshgupta20 @ridsuteri

Validations added to contact-form

---

assets/js/wordCounter.js

This issue is related with word counter project
Closes: #786
I have Solved an error in the word counter project , previously it was showing the wrong number count for the words type in the input box.
NA

Word Counter Issue solved

---

assets/css/slider.css
assets/css/sliderDemo.css
assets/js/slider.js
public/slider.html
script.js

- [GSSOC'21] Added a new project of a slider in JavaScript for animation of navbars
Closes: #1054
I've made a JavaScript project slider animation using APIs. This API will let the user to click on a button and see four different animations from right,left,top,bottom directions. It will help for nav bar animations which many beginners find difficult to code at the first time. I have used plain JavaScript for this project and the API is made by me as the name of Pushbar where the function of animation is taking place through open() and close() functions. 
NA

Added slider-js project (#1054)

---

assets/css/styles.css
index.html

- About Page design improvement
I have played around with few css properties and that proved to be enough for this webpage to look good.
NA

improved About page

---

index.html

- **_3 Github Logo issue fixed_**
Closes: #1075
I have fixed the 3 github logo issue in the index page
Fixed 3 Github Logo issue on the index page
**_BEFORE_**
**_AFTER_**

3 Github Logo issue

---

.github/workflows/auto-reply.yml

 Added auto response when pr is merged

---

assets/css/signuplogin.css

Closes: #1259 
I had updated css styles of signup-login page.
Also, i had properly identated code & fixed issue!
NA

Responsive Issue Fixed!

---

404.html

Added Error page

---

index.html

Fixes #1089 
Screenshot Reference:

positioning of toggle button

---

contact.html

- there was an unwanted Github Logo 
Closes: #1265
there was two github logos which was not required there .so, i just fixed that issue.
NA
**_BEFORE_**
**_AFTER_**

contact issue fixed

---

assets/css/Smooth_scroll.css
assets/js/Smooth_scroll.js
public/Smooth_scroll.html
script.js

Closes: #1211
I made a dummy website in which I made the scrolling of navbar items smooth.
https://user-images.githubusercontent.com/61948033/117379804-ee1c8880-aef5-11eb-9b98-7aa9749c54ac.mp4

Added Smooth Scroll Project

---

public/animated-navbar.html
script.js

- Added Animated Navbar Project using JavaScript
Closes: #[1342]
I've added a JavaScript of Animated Navbar project by using animations in CSS and JavaScript.
NA
Please review this PR and let me know if there are any conflicts @ridsuteri @991rajat @harshgupta20

added animated-navbar project #1342

---

assets/css/styles.css

The Contact now button broken in two parts. Also in the landing page, right side of navbar, three github icon is there with same information.
Closes: #1262 
Fixed the breaking of contact us button
NA

Fixed the breaking of contact us button

---

assets/css/Weather.css
assets/js/Weather.js
public/Weather.html
public/Weather_app.html

Closes: #1302 
Using HTML, CSS, and JavaScript to create a fully functional weather app.
Also added humidity, wind speed as well as the weather condition fully responsive with images.
NA

Weather App

---

assets/css/meme_sound.css
assets/js/meme_sound.js
public/meme_soundboard.html

meme sound board updated
Closes: #1082
https://user-images.githubusercontent.com/67833077/119503245-643f3d00-bd88-11eb-9735-5b073c7309d0.mp4

meme sound board updated

---

assets/js/3DTexture.js
public/3DTexture.html

Closes: #1712 
Added controls over the texture cube
NA

texture controls

---

assets/js/3DCube.js
public/3DCube.html

Closes: #1700 
Added orbit controls to 3D cube
NA

3D cube oribit controls

---

index.html

Closes: #1677 
Added Chatbot
NA

Add Chatbot

---

assets/css/Dynamicquotegenerator.css
assets/js/Dynamicquotegenerator.js
public/Dynamic-quotegenerator.html

Closes: #1318 
Added more color options for Quote Generator.
NA

More Conversion(Colors) are added

---

public/icons.html
public/loadingscreen.html

Closes: #1653
I have added the social media icons using the hover effect. @Vishal-raj-1 Kindly review it. 
A file named html loading screen has also been added by mistake. Kindly guide me how to remove it.  …

Social_Media icons

---

index.html

I have added a hovering effect on the Github button!

Added hovering effect on github button!

---

script.js

bug removed

---

index.html

social media links were not working so i fixed them

---

assets/css/styles.css
index.html

Updated the footer Layout
Added a About Us column which has the links for the team members, projects, and top contributors
Added hover animation and fixed colour problems regarding social media links

Footer update

---

README.md

Added LGM-SOC'21 Section #1799

---

projects.html

- Earlier Project Page Navbar doesn't consists of Signup/Login option.
Closes Issue #1808 
I have successfully added Signup/Login option in the Navbar section of the Project Page.

Signup/Login option in Project Page imported successfully

---

assets/css/styles.css

- Added Hover Effect to Buttons in the contact page.
Closes: #1820 
Added "background color : rgba(51, 51, 51, 0.726)" to "Send" and "Back" buttons in the hover state in contact page. 
NA

Hover effect

---

assets/css/styles.css

- Update homeProjects Section
Closes: #1809 
Made changes is "assets/css/styles.css"
1. .projectDescription p{
margin-bottom: 30px; // changed margin-bottom to 30px from 20px;
text-align: justify;  // changed text alignment from center to justify; 
}
2. a.button{
margin-left: 210px; //Added left margin to button
}
NA
Before  committing the changes :
After making the changes :

Updated homeProjects Section

---

assets/css/styles.css

Corrected the padding in the mobile view.
Closes: #182

Corrected mobile-size padding

---

index.html
signuplogin.html

- Earlier "About" and "Project" links in the footer section were not working properly as they were just taking us to the top of the page.
Closes Issue #1837 
I have successfully imported changes such that both the links are redirecting the user respectively to the "About us" and "Projects" page.
https://user-images.githubusercontent.com/61961107/123105428-6f53be80-d455-11eb-9eea-4e0fe2aa3725.mp4

About and Projects Links working in footer section

---

assets/css/signuplogin.css
signuplogin.html

- Added the show and hide password feature in sign in and sign up page
Closes: #1694

Show hide password

---

signuplogin.html

Repetition of sign-in, sign-up div
Closes: #1845 
Removed the redundant div from html file of sign-in login page
NA

Removed extra sign-in div

---

contact.html
index.html
projects.html

- Changed the Positon of Dark-Mode Toggler
Closes: #1847 will be closed through this PR(Position of Dark Mode icon #1847)
Changed the Positon of Dark-Mode Toggler and placed it just above the scroll to top toggler
NA
- [✔️ ] My code follows the style guidelines of this project.
- [✔️ ] I have performed a self-review of my own code.
- [✔️ ] I have commented my code, particularly in hard-to-understand areas.
- [✔️ ] I have made corresponding changes to the documentation.
- [✔️ ] New and existing unit tests pass locally with my changes.

Changed the Positon of Dark-Mode Toggler

---

index.html

Social media links corrected

---

assets/css/signuplogin.css
signuplogin.html

Closes: #1841
Added darkmode in signuplogin html.

added darkmode in signuplogin.html

---

index.css
index.html
index.js

- Separating css and js code from index.html
Closes: #1869
- I have separated css and javascript codes from index.html file and moved them to separate index.css and index.js files.
- NA

index.css and index.html added

---

assets/js/scripts.js
index.html

- Active link : highlight which link is active in navbar
Closes: #1668 
I've made changes in script.js file and index.html

linksActive

---

assets/css/Movie-Search-App.css
assets/js/Movie-Search-App.js
public/Movie-Search-App.html

- Show recommended movies based on current search
Closes: #1858 
Added new functions for getting and showing recommendations based on the first movie retrieved from the search. The recommendation only appear when a search is made.
NA

feat: add movie recommendations based on current search

---

contact.html
index.html
projects.html

- Position of Darkmode icon on contact and projects page
Closes: #1876 
I have fixed the position of Darkmode widget on contact and projects pages and refactored the respective HTML pages a bit.
NA
Projects section
Zoomed in projects section:
Contact Section:
Zoomed in contact section:

fix: position of darkmode widget on contact and projects page

---

RGB Color.css
assets/css/signuplogin.css
assets/css/styles.css
index.css

Fixed issue #1551 
I added the Ripple Effect on clicking the button. On every button I added this feature so it gives Nice view whenever user clicking on button.
NA

Added RippleEffect on Clicking Buttons

---

script.js

- Removed Duplicate Projects
Closes: #1795 will be closed through this PR(some projects are displayed twice. #1795)
Removed Duplicate Projects
NA
- [✔️ ] My code follows the style guidelines of this project.
- [ ✔️] I have performed a self-review of my own code.
- [ ✔️] I have commented my code, particularly in hard-to-understand areas.
- [✔️ ] I have made corresponding changes to the documentation.
- [ ✔️] New and existing unit tests pass locally with my changes.

Removed Duplicates

---

public/Restaurant.html

Closes: #1885
added the right address for our menu section in Restaurant website
NA

removed the bug which causes redirecting to blank page.

---

contact.html

- I added validation in the contact us form
Closes: #1891 
I added email validation function and a message popup if email is not entered correctly.
NA

Added email validation and activated other validation in contact us form

---

index.html

Added Twitter Handle

---

assets/css/styles.css
index.html

fixed the homepage looking bad on mobile plus formatted the index

fix for homepage looking bad on mobile

---

assets/css/Guess_My_Number.css
assets/js/Guess_My_Number.js
public/Guess_My_Number.html

Guess My Number project : it's a simple project when the goal is to guess a random number between 1 to 20.
each time you guess wrong your score will be reduced by one ( starting from 20 ).
when you guess wrong you can see a text saying either your guess is higher than the goal or lower.
I made changes in 3 files ( created 3 new files ) which are :
- Guess_My_Number.html
- Guess_My_Number.css
- Guess_My_Number.js

Guess My Number project

---

README.md

This resource has a wealth of resources for JavaScript beginners and learners.

Certified Course to Build Candidates Resume

---

assets/css/styles.css

When in Mobile view, the Learn Web Development box in Mobile view goes to the second line which makes the UI a bit bad experience.
Closes: #1936
I have changed the font-size of the text which changes according to the screen size and it will adjust automatically for the web app
NA

overflow bug in Learn Web Development fixed
